### PR TITLE
Building with responsive

### PR DESCRIPTION
**Pull request by SantiagoGuerra**
- Responisive web design
- Project finished
- 3 Breakpoints
- Mobile first

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi Santiago Guerra, nice, job!

There is  an update that need to be made.

- [x] There are no linter checks on this project; check [stickler's website](https://stickler-ci.com/) to see if the project is turned on.

 -  **After implementing this update, ensure that linter checks are passed, then submit another form for code review**

#### **```Have a nice day```** :slightly_smiling_face:

**Comment by SantiagoGuerra** [comment]
hello @uche-inyama , we have configured everything from the beginning, but the linter is not shown.
Screenshot from 2019-10-01 23-33-03

**Review by whiz25 — APPROVED** [review]
## Good job :clap: 
I don't see any requirements that you haven't met. All checks have passed so you can go ahead and merge to master.
Good luck in your next projects.

**Comment by SantiagoGuerra** [comment]
hi @whiz25 . How is your name? because we need to fill the form

**Comment by whiz25** [comment]
Martin Afani

**Comment by whiz25** [comment]
Martin Afani

**Pull request merged**
